<a href="https://colab.research.google.com/github/AnuragBalasahebChumble/BasicAssignments/blob/main/PythonBasicAsignment7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Write a Python Program to Add Two Matrices?

In [2]:
import numpy as np

mat1 = np.array([[1,1,1],
        [2,2,2],
        [3,3,3]])
mat2 = np.array([[0,0,0],
        [1,1,1],
        [2,2,2]])

Matsum = np.add(mat1,mat2)

print(f"The Sum of two matrix \n\n{mat1}  and \n\n{mat2}  is \n\n{Matsum} ")

The Sum of two matrix 

[[1 1 1]
 [2 2 2]
 [3 3 3]]  and 

[[0 0 0]
 [1 1 1]
 [2 2 2]]  is 

[[1 1 1]
 [3 3 3]
 [5 5 5]] 


Q2. Write a Python Program to Multiply Two Matrices?

In [5]:
mat1 = np.array([[1,1,1],
        [2,2,2],
        [3,3,3]])
mat2 = np.array([[0,0,0],
        [1,1,1],
        [2,2,2]])

matMul = np.dot(mat1,mat2)

print(f"The Sum of two matrix \n\n{mat1}  and \n\n{mat2}  is \n\n{matMul} ")

The Sum of two matrix 

[[1 1 1]
 [2 2 2]
 [3 3 3]]  and 

[[0 0 0]
 [1 1 1]
 [2 2 2]]  is 

[[3 3 3]
 [6 6 6]
 [9 9 9]] 


Q3. Write a Python Program to Transpose a Matrix?

In [ ]:
def Matrix(n,v=0):
    M=[]             
    for i in range(n):
        
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def crMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def prMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 

def tpMatrix(M,n,result):
    for i in range(n):
        for j in range(n):
            result[i][j]= M[j][i]
    return result

n=int(input("Enter N for N x N matrix: "))       
M1 = crMatrix(n)

print("Display Array M1 In Matrix Form")
prMatrix(M1,n)

result = Matrix(n)
result = tpMatrix(M1,n,result)
print("Transposed Matrix")
for r in result:
    print(r)  

Q4. Write a Python Program to Sort Words in Alphabetic Order?

In [31]:
Arr = input("Enter string: ")

words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter string: Bajrang Bali
Bajrang
Bali


Q5. Write a Python Program to Remove Punctuation From a String?

In [1]:

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

Arr = input("Enter a string with punctuations")


rem_punc = ""
for i in Arr:
    if i not in punctuations:
        rem_punc = rem_punc + i

# display 
print(rem_punc)

Enter a string with punctuations!()anurag@3
anurag3
